import Head from 'next/head'
import { Inter } from "@next/font/google";
import styles from '@/styles/Home.module.css'
import MainMenu from "@/components/main_menu";

const inter = Inter({ subsets: ['latin'] })

export default function Menu() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <MainMenu />
      <main className={styles.main}>
        <h1 className={inter.className}>Menu page</h1>
        <button>Start game</button>
      </main>
    </>
  )
}
